name: Discord Report
on: push
jobs:
 post-to-discord:
   runs-on: ubuntu-latest
   steps:
   - name: Message discord
     uses: sepastianpopp/discord-action@releases/v2
     with:
       webhook: ${{ secrets.DISCORD_WEBHOOK }}
       message: ${{ github.actor }} has done a ${{ github.event_name }} to ${{ github.repository }} (commit= ${{ github.sha }})
